---
- name: Provision a machine
  hosts: 127.0.0.1
  user: ec2-user
  connection: local
  vars:
    enable_azure_compat: true
  roles:
    - system-base
    - role: azure-compat
      when: enable_azure_compat == "true"
    - docker
    - kubernetes
